### ISSUE TITLE
readme with build instructions

### ISSUE THREAD

**Issue by chalda** [kobeyu/VoiceMeeterWrapper#1]
Hey @tocklime 
just found this project and was hoping to adapt it to my needs with a different MIDI pad (thanks for uploading this either way!). would you mind adding the most rudimentary instructions on whats required to run, sorry i've never used C# or really built anything with .NET or windows env and just opening this project with Visual Studio 2019 (with full c#, .NET and windows sdk installed) didnt really allow me to build and run an executable just straight up.

**Comment by tocklime** [comment]
I'll give it a go, yeah. I guess I'll see if *I* can still compile it first...

**Comment by tocklime** [comment]
Ok, I've had a crack at it. It runs for me now (after nuget updates), but I don't have any midi devices attached to this computer, so I can't test it still works right now.

**Comment by chalda** [comment]
Hey, I actually got it working with VStudio 2019 after also updating my NuGet packages. I think Visual Studio offered to convert the way the dependencies are listed (which i did) which also allowed me to update them... 
I had a bit of an issue getting the project to run, some issue with assigning startup project although I was able to figure out which one it is from the project files. This would be useful to note in the readme tho :)
Again I was able to figure it out since its not much different from working with Java but a short readme describing some rudimentary prereqs to get this to work would still be nice :)
Overall thanks for the project, I was able to get this working with 0 modifications other than changing the name of the MIDI device. The mapping is obviously not 1:1 for the addresses but pressing buttons did stuff in VM so it seems to work fine.

**Comment by chalda** [comment]
On a sidenote, I might make some modifications like assigning steps to midi controllers (like i only want volumes of -60 -3 0 3 6) etc this is possible with 0X-MIDI i think as well but i think would be useful here as well.

**Comment by tocklime** [comment]
Glad to hear it worked with a different device :).

Steps sound reasonable. Feel free to have at it, but I might have opinions on how to express it in the config. The obvious one is to extend the range syntax, so it doesn't just take start and end values, but maybe a step (`[1,3..20]`) or even a complete list of acceptable values (`[-60,-30,0,3,6]`). Converting into that might be interesting. How best to map `[0..127]` on to `[-60,-30,0,3,6]`?

**Comment by chalda** [comment]
I guess the configs are pretty specialized as everyone has different audio setups in VM (i dont really care about any of the hardware inputs for example just virtual ones). Ill add mine as an alternative example. One way to normalize the MIDI devices would be to work against LoopBe1 + 0X-MIDI or some other virtual midi cable. Although this obviously adds extra software/dependencies.

yep extending the range syntax is what i was gonna take a crack at, although that is a good point, might not cleanly map into the midi values. i guess something like: `step = ceil(128/array.length)`

Some other feature ideas:
Having a 0 value on double tap (similar to how VM it self works, where if you double tap a slider it just resets to 0) although this might just have to a separate button since it might not be easy to tell these inputs apart. As well as having the app startup and set default values (bring everything down to 0 for example on wake).

**Comment by tocklime** [comment]
the trouble with bringing down to zero on boot is that it's then out of sync with the physical sliders on my midi board. Potentially config-able, I suppose, to have an optional on-startup behaviour.

**Comment by chalda** [comment]
Ahhhhh interesting. I didn't even think of that as my drum pad is all just
led indicators with no physical sliders. I'll think about how to make it
work. Mostly I am just ocd and don't like leaving the sliders with any
values on them (plus I doubt it helps the audio quality to do post
processing to increase dB)

One thing I noticed is that using the midi device and setting to 0 actualy
sets the slider to 0.0 and leaves it red (as in modified) as oppose to the
neutral state that just says 0 dB. Obviously effectively this is equivalent
but just looks weird.
