### ISSUE TITLE
License Request

### ISSUE THREAD

**Issue by xathon** [kobeyu/VoiceMeeterWrapper#3]
I really appreciate the work you did for the C# wrapper and I'd like to use it in a project of my own. This is why I'd like to ask you to add a license to the project (for example the [MIT License](https://choosealicense.com/licenses/mit/), the [Unlicense ](https://choosealicense.com/licenses/unlicense/) or [CC BY](https://creativecommons.org/licenses/by/4.0/) ). Thank you in advance.

**Comment by tocklime** [comment]
Let me know what you get up to with it!

**Comment by xathon** [comment]
Thank you! It will be used for an audio routing application that uses VoiceMeeter and TeamSpeak (I'll put it up on GitHub too).
